import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import SmoothScroll from "@/components/ui/SmoothScroll";
import HeroHeader from "./comp/Navbar";

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
  title: "Verito Studio Social Media, Content & Website Development Agency",
  description:
    "Verito Studio helps startups, small businesses, and personal brands grow with creative social media management, high-impact content creation, and premium website development. Build your digital identity and 10× your online presence.",
  keywords: [
    "social media agency",
    "content creation",
    "website development",
    "branding agency",
    "Next.js websites",
    "digital marketing",
    "short form content",
    "SMM agency India",
    "startup branding",
    "Verito Studio",
  ],
  icons: {
    icon: '/favicon.png', // or '/favicon.png'
  },
  openGraph: {
    title: "Verito Studio — Crafting Digital Brands That Stand Out",
    description:
      "We build powerful digital identities through social media, content creation, and stunning websites that help your brand stand out and grow.",
    url: "https://veritostudio.com",
    siteName: "Verito Studio",
    images: [
      {
        url: "/images/image.png", 
        width: 1200,
        height: 630,
        alt: "Verito Studio — Digital Branding & Creative Agency",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Verito Studio — Digital Branding & Creative Agency",
    description:
      "Premium Social Media, Content & Web Development Agency helping brands scale their online presence.",
    images: ["/images/image.png"],
  },
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        <HeroHeader />

         {/* <SmoothScroll> */}
        {children}
         {/* </SmoothScroll> */}
      </body>
    </html>
  );
}
